// Project/reactjs/src/App.js
import './App.css';
import React from 'react';

class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = { ret : "" , username : "", password : "", path : ""};

    this.updateUsername = this.updateUsername.bind(this);
    this.updatePassword = this.updatePassword.bind(this);
    this.updatePath = this.updatePath.bind(this);
    this.loginUser = this.loginUser.bind(this);
    this.showXSS = this.showXSS.bind(this);
    this.pathTraversal = this.pathTraversal.bind(this);
  }

  updateUsername(evt) {
    this.setState({username: evt.target.value});
  }

  updatePassword(evt) {
    this.setState({password: evt.target.value});
  }

  updatePath(evt) {
    this.setState({path: evt.target.value});
  }

  loginUser() {
    fetch(`/api/login`, {
      method: 'POST',
      headers: {'Content-Type': 'application/json'},
      body: JSON.stringify({"username": this.state.username, "password": this.state.password})
    }).then(response => response.json())
    .then(data => (this.setState({ret: data.message})));
  }

  showXSS() {
    fetch(`/api/show_xss`, {
      method: 'GET',
      headers: {'Content-Type': 'application/json'},
    }).then(response => response.json())
    .then(data => (this.setState({ret: data.message})));
  }

  pathTraversal() {
    fetch(`/api/path_traversal`, {
      method: 'POST',
      headers: {'Content-Type': 'application/json'},
      body: JSON.stringify({"path": this.state.path})
    }).then(response => response.json())
    .then(data => (this.setState({ret: data.message})));
  }


  render() {
    return (
      <div className="App">
        <header className="App-header">
          <div>
            <div>
              <div>
                <h2>Login</h2>
                  <form>
                    <div>
                      <div>
                        <input type="username" name="username" id="username" placeholder="username" onChange={this.updateUsername}/>
                      </div>
                      <div>
                        <input type="password" name="password" id="password" placeholder="password" onChange={this.updatePassword}/>
                      </div>
                    </div>
                    <button type="button" onClick={this.loginUser} >Login</button>
                  </form>
                  <div>
                    <input type="text" name="path" id="path" placeholder="path" onChange={this.updatePath}/><br></br>
                    <button type="button" onClick={this.showXSS} >XSS hack</button>
                    <button type="button" onClick={this.pathTraversal} >Path traversal hack</button>
                  </div>
                  <div dangerouslySetInnerHTML={{__html: this.state.ret}}></div>
              </div>
            </div>
          </div>
        </header>
      </div>
    );
  }
}

export default App;

// Project/secure/angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';

import { Pipe, PipeTransform } from "@angular/core";
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';

@Pipe({
  name: 'sanitizeHtml'
})
export class SanitizeHtmlPipe implements PipeTransform {

  constructor(private _sanitizer:DomSanitizer) {
  }

  transform(v:string):SafeHtml {
    return this._sanitizer.bypassSecurityTrustHtml(v);
  }
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  constructor(private http: HttpClient) {}
  username_login = '';
  password_login = '';
  safeness_login = 0;

  username_xss = '';
  safeness_xss = 0;

  username_lfi = '';
  path_lfi = '';
  safeness_lfi = 0;

  ret = '';
  ret_html = '';

  clear_all() {
    this.username_login = '';
    this.password_login = '';
    this.safeness_login = 0;

    this.username_xss = '';
    this.safeness_xss = 0;

    this.username_lfi = '';
    this.path_lfi = '';
    this.safeness_lfi = 0;

    this.ret = '';
    this.ret_html = '';
  }

  loginUser() {
    const data = {"username": this.username_login, "password": this.password_login, "safeness": this.safeness_login};
    this.http.post('/api/login', data).subscribe((response: JSON) => {
      this.clear_all();
      this.ret = response["message"]
    });
  }

  xss() {
    const data = {"username": this.username_xss, "safeness": this.safeness_xss};
    this.http.post('/api/show_xss', data, { observe: 'response' }).subscribe((response) => 
    {
      this.clear_all();
      if (response.headers.get('Content-Type') == 'text/plain') {
        this.ret_html = response.body["message"]
      } else {
        this.ret = response.body["message"]
      }
    });
  }

  pathTraversal() {
    const data = {"username": this.username_lfi, "path": this.path_lfi, "safeness": this.safeness_lfi};
    this.http.post('/api/path_traversal', data).subscribe((response: JSON) => {
      this.clear_all();
      this.ret = response["message"];
    });
  }
}

<div>
        <div>
                <div>
                        <h2>Login</h2>
                        <form>
                                <div>
                                        <div>
                                                <input type="username" name="username_login" id="username_login" placeholder="username" [(ngModel)]="username_login"/>
                                        </div>
                                        <div>
                                                <input type="password" name="password_login" id="password_login" placeholder="password" [(ngModel)]="password_login"/>
                                        </div>
                                        <div>
                                                <select [(ngModel)]="safeness_login" name="safeness_login" id="safeness_login">
                                                        <option value="0">No sanitization</option>
                                                        <option value="1">Only letters and numbers</option>
                                                        <option value="2">Sanitize \'</option>
                                                        <option value="3">Hash inputs</option>
                                                </select>
                                        </div>
                                </div>
                                <button type="button" (click)="loginUser()">Login</button>
                        </form>
                </div>
                <div>
                        <h2>XSS</h2>
                        <form>
                                <div>
                                        <div>
                                                <input type="username" name="username_xss" id="username_xss" placeholder="username" [(ngModel)]="username_xss"/>
                                        </div>
                                        <div>
                                                <select class="form-control" [(ngModel)]="safeness_xss" name="safeness_xss" id="safeness_xss">
                                                        <option value="0">No sanitization</option>
                                                        <option value="1">Sanitize special characters</option>
                                                        <option value="2">Add headers</option>
                                                </select>
                                        </div>
                                </div>
                                <button type="button" (click)="xss()">XSS</button>
                        </form>
                </div>
                <div>
                        <h2>Path Traversal</h2>
                        <form>
                                <div>
                                        <div>
                                                <input type="username" name="username_lfi" id="username_lfi" placeholder="username" [(ngModel)]="username_lfi"/>
                                        </div>
                                        <div>
                                                <input type="text" [(ngModel)]="path_lfi" name="path_lfi" id="path_lfi" placeholder="path" />
                                        </div>
                                        <div>
                                                <select class="form-control" [(ngModel)]="safeness_lfi" name="safeness_lfi" id="safeness_lfi">
                                                        <option value="0">No sanitization</option>
                                                        <option value="1">Sanitize special characters</option>
                                                        <option value="2">Hash name of file</option>
                                                        <option value="3">Check database</option>
                                                </select>
                                        </div>
                                </div>
                                <button type="button" (click)="pathTraversal()">PathTraversal</button>
                        </form>
                </div>
                <div [innerHTML]="ret | sanitizeHtml"></div>
                <div [innerHTML]="ret_html"></div>
        </div>
</div>
